## 3. Operazioni su array

Crea un array a, 1D (senza digitarlo esplicitamente), e genera due nuovi array b, contenente una sottostringa a piacere e c che è il reverse dell'array a (esempio [1,2,3] diventa [3,2,1]) . Dividi l'array a per l'array c. Fai la stessa cosa per una lista.

In [ ]:
%conda install numpy

2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 26.3.2
    latest version: 26.5.3

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

1. Creare un array a monodimensionale 

In [23]:
a = np.arange(1, 5)
a

array([1, 2, 3, 4])

2. Genero un nuovo array b, partendo da a

In [33]:
b = a[1:4]
b

array([2, 3, 4])

3. Genero un nuovo array c dato dall'inversione di a

In [41]:
c = a[::-1]
c

array([4, 3, 2, 1])

4. Divido l'array a per l'array c

In [26]:
a / c

array([0.25      , 0.66666667, 1.5       , 4.        ])

5. Faccio le stesse cose solo usando le liste di python

In [36]:
lista_a = list(range(1, 5))
lista_a

[1, 2, 3, 4]

In [37]:
lista_b = lista_a[1:4]
lista_b

[2, 3, 4]

In [38]:
lista_c = lista_a[::-1]
lista_c

[4, 3, 2, 1]

In [40]:
# lista_a / lista_c genera un TypeError
[lista_a[i] / lista_c[i] for i in range(len(lista_a))]

[0.25, 0.6666666666666666, 1.5, 4.0]