## 1. Indicizzazione booleana

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: 2, 3, 5, 7, 11, 13, 17, 19.

2. Utilizza un test logico (ad esempio >, <, ==, !=) per selezionare tutte le voci del vettore maggiori di 10.

3. Utilizza un test logico per selezionare tutti i numeri primi pari dalla lista.

In [ ]:
%conda install numpy

2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 26.3.2
    latest version: 26.5.3

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

1. Creare un nuovo vettore con tutti i numeri primi tra 0 e 20. I numeri primi compresi tra 0 e 20 sono: 2, 3, 5, 7, 11, 13, 17, 19.

In [3]:
numeri_primi = np.array([2, 3, 5, 7, 11, 13, 17, 19])
numeri_primi

array([ 2,  3,  5,  7, 11, 13, 17, 19])

2. Utilizza un test logico (ad esempio >, <, ==, !=) per selezionare tutte le voci del vettore maggiori di 10.

In [4]:
numeri_primi[numeri_primi > 10]

array([11, 13, 17, 19])

3. Utilizza un test logico per selezionare tutti i numeri primi pari dalla lista.

In [10]:
numeri_primi[(numeri_primi & 1) == 0]

array([2])