## 5. Manipolazione di vettori

In [29]:
%conda install numpy

2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 26.3.2
    latest version: 26.5.3

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [30]:
import numpy as np

1.Creare un vettore contenente i seguenti stipendi: 50.000, 105.250, 55.000, 89.000.
Qual è il costo totale del personale (somma di tutti gli stipendi dell'azienda)?

In [31]:
salary = np.array([50000, 105250, 55000, 89000])
salary_start_sum = salary.sum()
salary_start_sum

np.int64(299250)

2. Supponiamo che il nostro malvagio CEO abbia deciso di darsi un aumento.
Modifica il vettore degli stipendi in modo che il CEO, la persona che guadagna 105.250 dollari, riceva un aumento del 15%.

In [32]:
i = np.where(salary == 105250)[0]       # Indice della posizione del salario del CEO nell'array
salary[i] = salary[i] * 1.15
salary

array([ 50000, 121037,  55000,  89000])

3. Il 115% di 105.250 dollari è 121.037,50 dollari.
Questo valore è presente nel tuo array? Se no, riesci a capire il motivo? 

    Il motivo è che l'array salary, è un array di int, quindi convertirà il valore in int.

4. Ricrea il vettore e utilizza l'argomento dtype in modo che, quando il CEO riceve un aumento del 15%, il suo stipendio finale sia esattamente 121.037,50 dollari

In [33]:
salary = np.array([50000, 105250, 55000, 89000], dtype=float)

i = np.where(salary == 105250)[0] 
salary[i] = salary[i] * 1.15

salary

array([ 50000. , 121037.5,  55000. ,  89000. ])

5. Questo aumento ha infastidito l'impiegata con lo stipendio più basso (50.000 dollari), che ora pretende un aumento del 20%.
Modifica il vettore per riflettere questo cambiamento.

In [34]:
i = np.where(salary == 50000)[0]
salary[i] = salary[i] * 1.2

salary

array([ 60000. , 121037.5,  55000. ,  89000. ])

6. L'aumento dato al CEO e all'impiegata ha irritato gli altri due dipendenti, quindi ora devono ricevere un aumento del 10%.
Modifica il vettore di conseguenza.

In [35]:
salary[2::] = salary[2::] * 1.1

salary

array([ 60000. , 121037.5,  60500. ,  97900. ])

7. Calcola il costo totale del personale dopo tutti gli aumenti.
Alla fine, quanto è costato all'azienda l'aumento di circa 16.000 dollari del CEO?

In [36]:
salary_end_sum = salary.sum()
salary_end_sum

np.float64(339437.5)

In [37]:
# Calcolo la differenza tra la somma all'inizio e dopo la cascata di aumenti dei dipendenti
salary_end_sum - salary_start_sum

np.float64(40187.5)