## 7. Analisi di una matrice

In [2]:
%conda install numpy

2 channel Terms of Service accepted
Retrieving notices: done
Channels:
 - defaults
Platform: linux-64
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 26.3.2
    latest version: 26.5.3

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

Data la matrice survey con età, reddito e anni di istruzione

In [3]:
survey_matrix = np.array([ [25, 40000, 10], [32, 52000, 12], [40, 63000, 14], [29, 47000, 11], [35, 58000, 13] ])
survey_matrix

array([[   25, 40000,    10],
       [   32, 52000,    12],
       [   40, 63000,    14],
       [   29, 47000,    11],
       [   35, 58000,    13]])

1. Seleziona dalla matrice solo gli intervistati con almeno 12 anni di istruzione utilizzando un test logico.

In [5]:
survey_high_instruction = survey_matrix[survey_matrix[:, 2] >= 12]
survey_high_instruction

array([[   32, 52000,    12],
       [   40, 63000,    14],
       [   35, 58000,    13]])

2. In un'unica riga di codice, seleziona i redditi degli intervistati con almeno 12 anni di istruzione

In [8]:
salary_high_instruction = survey_high_instruction[:, 1]
salary_high_instruction

array([52000, 63000, 58000])

3. In un'unica riga di codice, calcola il reddito medio degli intervistati con almeno 12 anni di istruzione

In [10]:
mean_salary = np.mean(salary_high_instruction)
mean_salary

np.float64(57666.666666666664)