## 2. Operazioni su array

Crea un array a, 2D (senza digitarlo esplicitamente), e genera due nuovi array b, contenente la sua 2ª e 4ª riga, e c contenente solo la 3ª. Dividi ogni colonna dell'array a, elemento per elemento, con l'array c.

In [ ]:
%conda install numpy

2 channel Terms of Service accepted
Channels:
 - defaults
Platform: linux-64
Solving environment: done


==> WARNING: A newer version of conda exists. <==
    current version: 26.3.2
    latest version: 26.5.3

Please update conda by running

    $ conda update -n base -c defaults conda



# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [ ]:
import numpy as np

In [27]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
b = a[[1, 3]]       # Prendo la seconda e la quarta riga di a
b

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [30]:
c = a[2]            # Prendo la terza riga di a
c

array([10, 11, 12, 13, 14])

Divido ogni colonna di a, elemento per elemento, con l'array c

In [34]:
(a.transpose() / c).transpose()

array([[0.        , 0.1       , 0.2       , 0.3       , 0.4       ],
       [0.45454545, 0.54545455, 0.63636364, 0.72727273, 0.81818182],
       [0.83333333, 0.91666667, 1.        , 1.08333333, 1.16666667],
       [1.15384615, 1.23076923, 1.30769231, 1.38461538, 1.46153846],
       [1.42857143, 1.5       , 1.57142857, 1.64285714, 1.71428571]])